### ISSUE TITLE
Flash Loan Sensible

### ISSUE THREAD

**Issue by 0xAaCE** [stabilize-token/contracts#1]
I think that you are open to a Flash Loan Hack here. If somebody manipulate the price of one of the token and later call this method, he will be manipulating the rewards assignation for every pool. 

https://github.com/stabilize-token/contracts/blob/eea1639f89dc623fddfd958ff24e2f6777440a63/contracts/Operator.sol#L743

**Comment by happypsyduck** [comment]
Prices oracles used by this function are sourced from Chainlink which are resistant to flash loans.
